// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1lGdHblg4nV697_3Dr0QKmNlgq2FpH0',
    appId: '1:119335573202:web:eef2317beeeac2c6037f0b',
    messagingSenderId: '119335573202',
    projectId: 'calendar-lotus',
    authDomain: 'calendar-lotus.firebaseapp.com',
    storageBucket: 'calendar-lotus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfUrcR0Z1Rskj8WJEVrSoVRxL1QayFtw',
    appId: '1:119335573202:android:be7ddc0a825d2dfd037f0b',
    messagingSenderId: '119335573202',
    projectId: 'calendar-lotus',
    storageBucket: 'calendar-lotus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYlBH7iXD2k2f3ylrUfp4AzxwbyPhFWgY',
    appId: '1:119335573202:ios:2c1b565b7c0446f3037f0b',
    messagingSenderId: '119335573202',
    projectId: 'calendar-lotus',
    storageBucket: 'calendar-lotus.appspot.com',
    iosBundleId: 'com.example.p1LoginFirebase',
  );
}
